name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  sync_commands:
    name: Sync commands to Discord
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn sync-commands
        env:
          DISCORD_APP: ${{ secrets.DISCORD_APP }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
